auto lo
iface lo inet loopback

iface ens33 inet manual

auto vmbr0
iface vmbr0 inet static
#       address 192.168.1.217/24
#       gateway 192.168.1.1
#       address 10.59.200.200/16
#       gateway 10.59.0.1
#       address 192.168.100.230/24
#       gateway 192.168.100.1
        address 10.20.111.111/16
        gateway 10.20.0.1 
#       address 172.31.99.99/23
#       gateway 172.31.98.1
        bridge-ports ens33
        bridge-stp off
        bridge-fd 0